// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmgqrzdohvlhitcipikc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZ3FyemRvaHZsaGl0Y2lwaWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTU0NjYsImV4cCI6MjA2NTIzMTQ2Nn0.RA3V_AoJ9yQIRryzkm4W1U1WH53vOTeSYcsVsCAJoiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);